# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-10 00:47
from __future__ import unicode_literals

import catalog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', sorl.thumbnail.fields.ImageField(upload_to=catalog.models.upload_cover, verbose_name='Постер')),
                ('thumb_cover', sorl.thumbnail.fields.ImageField(upload_to='media/')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('slug', models.SlugField(verbose_name='Алиас')),
                ('is_open', models.BooleanField(help_text='Дать доступ к файлу для всех пользователей', verbose_name='Для всех')),
                ('is_slug', models.BooleanField(help_text='Файл будет доступет только по ссылке', verbose_name='По ссылке')),
                ('is_for_me', models.BooleanField(help_text='Файл будет доступен только Вам', verbose_name='Только для меня')),
            ],
            options={
                'verbose_name_plural': 'Файлы',
                'verbose_name': 'Файл',
                'db_table': 'catalog',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(verbose_name='Алиас')),
                ('is_publish', models.BooleanField(default=False, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ExpresFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, default=catalog.models.randomStr, max_length=25, null=True, verbose_name='Алиас')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name_plural': 'Временные файлы',
                'verbose_name': 'Временные файлы',
                'db_table': 'expresfiles',
            },
        ),
        migrations.CreateModel(
            name='FilesCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_s', models.FileField(upload_to='media/', verbose_name='Файл')),
                ('catalog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Catalog')),
            ],
            options={
                'verbose_name_plural': 'Файлы',
                'verbose_name': 'Файл',
                'db_table': 'files_catalog',
            },
        ),
        migrations.CreateModel(
            name='FilesExpres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_s', models.FileField(upload_to='media/', verbose_name='Файл')),
                ('expresfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ExpresFiles', verbose_name='Временные файлы')),
            ],
            options={
                'verbose_name_plural': 'Файлы',
                'verbose_name': 'Файл',
                'db_table': 'files',
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
