# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161209_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpresFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('slug', models.SlugField(verbose_name='Алиас')),
                ('date_add', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
            ],
            options={
                'verbose_name': 'Временные файлы',
                'verbose_name_plural': 'Временные файлы',
                'db_table': 'expresfiles',
            },
        ),
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, verbose_name='Алиас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(verbose_name='Алиас'),
        ),
        migrations.AlterField(
            model_name='files',
            name='slug',
            field=models.SlugField(verbose_name='Алиас'),
        ),
        migrations.AddField(
            model_name='files',
            name='expresfile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.ExpresFiles', verbose_name='Временные файлы'),
        ),
    ]
