# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20161209_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='expresfiles',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=300, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
